num_workers: 8
test_freq: 5
benchmark:
  name: ucf101-retrieval
dataset:
  name: ucf101
  batch_size: 16
  fold: 1
  video_clip_duration: 0.5
  video_fps: 16.0
  transforms: crop+color
  crop_size: 224
  audio_clip_duration: 1.0
  audio_srate: 16000
  spec_params:
    n_fft: 512
    hop_length: 256
    n_mels: 128
  train:
    split: trainlist{fold:02d}
    use_augmentation: false
    drop_last: false
    use_shuffle: false
    mode: video
    clips_per_video: 10
  test:
    split: testlist{fold:02d}
    use_augmentation: false
    use_shuffle: false
    drop_last: false
    mode: video
    clips_per_video: 10
