resume: true
test_only: false
num_workers: 8
test_freq: 1
print_freq: 100
dataset:
  name: vggsound
  batch_size: 32
  video_clip_duration: 1.0
  video_fps: 16.0
  transforms: msc+color
  crop_size: 224
  audio_clip_duration: 2.0
  audio_srate: 16000
  spec_params:
    n_fft: 512
    hop_length: 256
    n_mels: 128
  tfmask_params:
    time_mask_ratio: 0.2
    time_mask_size: 5
    freq_mask_ratio: 0.2
    freq_mask_size: 3
    var_masks: true
  train:
    split: train_subset
    use_augmentation: true
    drop_last: true
    clips_per_video: 5
    video_only: true
  test:
    split: test
    use_augmentation: false
    drop_last: true
optimizer:
  name: adam
  weight_decay: 1.0e-06
  num_epochs: 100
  lr:
    name: multistep
    base_lr: 0.0005
    gamma: 0.9
    milestones:
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
    - 80
    - 90
model:
  name: VGGSound-VICReg-Video
  model_dir: checkpoints/VGGSound
  arch: vicreg_v_wrapper
  args:
    exp_dim:
    - 4096
    - 4096
    - 4096
    video_backbone: R2Plus1d
    video_backbone_args:
      depth: 18
loss:
  name: VICLoss
  args:
    sim_coeff: 25.0
    std_coeff: 25.0
    cov_coeff: 1.0
